[global]
  sendAnonymousUsage = false

[log]
  # If something goes wrong, changing this to `DEBUG` might help you finding
  # out what happens.
  level = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"
  filePath = "/var/log/traefik.log"


[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers]
  # This is how you tell traefik that it has to get the dynamic config from a config file
  # Note that the path is the path to the file inside Docker, not insider your machine!
  # If you want do use Docker itself for this check traefik docs!

  # uncomment below if you want providers file 
  #[providers.file]
  #  filename = "/etc/traefik/traefik.config.toml"
  #  watch = true
  [providers.redis]
    endpoints = ["127.0.0.1:6379"]

[api]
  # With this you enable the web UI
  insecure = false
  dashboard = true

[http]
  [http.routers]
  #########################################################################
    # http #
    [http.routers.http-to-app]
      # You can change the rules here and make it more complex. Check traefik
      # docs!
      rule = "Host(`app.example.com`)"
      service = "app"
      entrypoints = ["http"]
      # enable if u want redirect to https 
      #middlewares = ["redirect"]

  ## https #
    [http.routers.https-to-app]
      rule = "Host(`app.example.com`)"
      service = "app"
      entrypoints = ["https"]
      middlewares = ["app-compress"]
      [http.routers.https-to-app.tls]

    [http.services]
    # service 
      [http.services.app]
        [http.services.app.loadBalancer]
        passHostHeader = true
          [[http.services.app.loadBalancer.servers]]
            # This is where your dev app lives.
            url = "http://url/"


  ########################################################################

  [http.middlewares]
    [http.middlewares.redirect.redirectScheme]
      scheme = "https"
      average = 100
      burst = 50
    [http.middlewares.app-compress.compress]


[tls]
  [[tls.certificates]]
    certFile = "/data/fullchain.pem"
    keyFile = "/data/privkey.pem"
